# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83f4ca02ec962fcd60bf039345f054544b56a25df1173768bb2c48cd23c652032710cd6a083a61bdf944ec72c7eca3c242293ec6d346323b2829b3ca3c421715

test:
  secret_key_base: 369f363f64f91f805abe9a7649f1612e00d95f7be55b874f517421b7901389f22a9a51ba6f54920f2b11a6893dfdeb80b9c45fc9e9e1470025190444f6d2df9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
